version: '3.8'
services:

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '6500:5432'

volumes:
  postgres: