export const enum ENV {
  PORT = 'PORT',
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_ACCESS_EXPIRES = 'JWT_ACCESS_EXPIRES',
  JWT_REFRESH_EXPIRES = 'JWT_REFRESH_EXPIRES',
}
